name: Feature Request
description: 建议新功能
title: '[Feature]: '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: '## 感谢你的建议！'

  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 你希望插件增加什么功能？
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: 使用场景
      description: 这个功能对你的群聊有什么帮助？
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 优先级感知
      options:
        - '高：严重影响使用'
        - '中：有更好，没有也能用'
        - '低：锦上添花'
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 实现建议
      description: 如有实现思路可描述于此
